import { internalMutation } from "./_generated/server";

// Map of university names to common abbreviations
const universityAbbreviations: Record<string, string> = {
  "Massachusetts Institute of Technology": "mit",
  "University of California, Berkeley": "berkeley",
  "Carnegie Mellon University": "cmu",
  "Georgia Institute of Technology": "gatech",
  "University of Washington": "washington",
  "Stanford University": "stanford",
  "University of Illinois at Urbana-Champaign": "illinois",
  "California Institute of Technology": "caltech",
  "University of Michigan": "umich",
  "Cornell University": "cornell",
  "Princeton University": "princeton",
  "Harvard University": "harvard",
  "Boston University": "bu",
  "Northeastern University": "northeastern",
  "Tufts University": "tufts",
  "Boston College": "bc",
  "Brandeis University": "brandeis"
};

// Helper function to create slug from university name
const createSlug = (name: string): string => {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')  // Replace non-alphanumeric with hyphens
    .replace(/(^-|-$)/g, '')      // Remove leading/trailing hyphens
    .replace(/--+/g, '-');        // Replace multiple hyphens with single one
};

// Helper function to create composite program ID
const createProgramId = (universityName: string, programId: string): string => {
  // Use abbreviation if available, otherwise create a slug
  const universitySlug = universityAbbreviations[universityName] || createSlug(universityName);
  return `${universitySlug}-${programId}`;
};

// Default export that safely seeds the database
export default internalMutation({
  handler: async (ctx) => {
    console.log("Deleting existing data from the database...");
    // Clear existing universities from the database first
    await ctx.db
      .query("universities")
      .collect()
      .then(existingUniversities => {
        return Promise.all(
          existingUniversities.map(university => 
            ctx.db.delete(university._id)
          )
        );
      });

    console.log("Initializing database with seed data...");

    // Seed universities data
    const universities = [
      {
        name: "Stanford University",
        location: {
          city: "Stanford",
          state: "California",
          country: "USA",
          region: "West Coast",
        },
        programs: [
          {
            id: createProgramId("Stanford University", "cs-ms"),
            name: "Computer Science",
            degree: "MS",
            department: "School of Engineering",
            requirements: {
              gre: true,
              greRequired: true,
              grePreferred: false,
              greWaiver: false,
              toefl: true,
              toeflMinimum: 100,
              ielts: true,
              ieltsMinimum: 7.0,
              minimumGPA: 3.5,
              applicationFee: 125,
              recommendationLetters: 3,
              statementRequired: true,
              cvRequired: true,
              writingSampleRequired: false,
              portfolioRequired: false,
            },
            deadlines: {
              fall: "December 1",
              spring: null,
              summer: null,
              priority: "November 15",
              funding: "December 1",
            },
            acceptanceRate: 0.05,
            tuition: 55000,
            duration: "1-2 years",
            website: "https://cs.stanford.edu/academics/masters",
            facultyStrengths: ["AI", "Systems", "Theory", "HCI"],
            researchAreas: ["Machine Learning", "Computer Vision", "Robotics"],
          },
          {
            id: createProgramId("Stanford University", "cs-phd"),
            name: "Computer Science",
            degree: "PhD",
            department: "School of Engineering",
            requirements: {
              gre: true,
              greRequired: true,
              grePreferred: false,
              greWaiver: false,
              toefl: true,
              toeflMinimum: 100,
              ielts: true,
              ieltsMinimum: 7.0,
              minimumGPA: 3.7,
              applicationFee: 125,
              recommendationLetters: 3,
              statementRequired: true,
              cvRequired: true,
              writingSampleRequired: true,
              portfolioRequired: false,
              interviewRequired: true,
            },
            deadlines: {
              fall: "December 1",
              spring: null,
              summer: null,
            },
            acceptanceRate: 0.03,
            tuition: 55000,
            duration: "5-6 years",
            website: "https://cs.stanford.edu/academics/phd",
            facultyStrengths: ["AI", "Systems", "Theory", "HCI"],
            researchAreas: ["Machine Learning", "Computer Vision", "Robotics"],
          },
          {
            id: createProgramId("Stanford University", "ai-ms"),
            name: "Artificial Intelligence",
            degree: "MS",
            department: "School of Engineering",
            requirements: {
              gre: true,
              greRequired: true,
              grePreferred: false,
              greWaiver: false,
              toefl: true,
              toeflMinimum: 100,
              ielts: true,
              ieltsMinimum: 7.0,
              minimumGPA: 3.5,
              applicationFee: 125,
              recommendationLetters: 3,
              statementRequired: true,
              cvRequired: true,
              writingSampleRequired: false,
              portfolioRequired: false,
            },
            deadlines: {
              fall: "December 1",
              spring: null,
              summer: null,
              priority: "November 15",
            },
            acceptanceRate: 0.04,
            tuition: 56000,
            duration: "1-2 years",
            website: "https://ai.stanford.edu/masters",
            facultyStrengths: ["Machine Learning", "Computer Vision", "NLP"],
            researchAreas: ["Deep Learning", "Reinforcement Learning", "AI Ethics"],
          },
          {
            id: createProgramId("Stanford University", "hci-ms"),
            name: "Human-Computer Interaction",
            degree: "MS",
            department: "School of Engineering",
            requirements: {
              gre: true,
              greRequired: false,
              grePreferred: true,
              greWaiver: true,
              toefl: true,
              toeflMinimum: 100,
              ielts: true,
              ieltsMinimum: 7.0,
              minimumGPA: 3.5,
              applicationFee: 125,
              recommendationLetters: 3,
              statementRequired: true,
              cvRequired: true,
              writingSampleRequired: false,
              portfolioRequired: true,
            },
            deadlines: {
              fall: "December 1",
              spring: null,
              summer: null,
            },
            acceptanceRate: 0.08,
            tuition: 55000,
            duration: "1-2 years",
            website: "https://hci.stanford.edu/academics/masters",
            facultyStrengths: ["Design Thinking", "UX Research", "Interactive Systems"],
            researchAreas: ["AR/VR", "Accessibility", "Social Computing"],
          },
        ],
        ranking: 4,
        website: "https://www.stanford.edu",
        description: "Stanford University is a private research university in Stanford, California, known for its academic strength, proximity to Silicon Valley, and ranking as one of the world's top universities.",
        admissionStats: {
          applicants: 7000,
          admitted: 350,
          enrolled: 200,
          acceptanceRate: 0.05,
          averageGPA: 3.9,
          averageGRE: {
            verbal: 165,
            quantitative: 168,
            analytical: 4.5,
          },
        },
        imageUrl: "https://storage.googleapis.com/gradaid-images/stanford.jpg",
      },
      {
        name: "Massachusetts Institute of Technology",
        location: {
          city: "Cambridge",
          state: "Massachusetts",
          country: "USA",
          region: "East Coast",
        },
        programs: [
          {
            id: createProgramId("Massachusetts Institute of Technology", "eecs-phd"),
            name: "Electrical Engineering and Computer Science",
            degree: "PhD",
            department: "School of Engineering",
            requirements: {
              gre: true,
              greRequired: true,
              grePreferred: false,
              greWaiver: false,
              toefl: true,
              toeflMinimum: 100,
              ielts: true,
              ieltsMinimum: 7.0,
              minimumGPA: 3.7,
              applicationFee: 75,
              recommendationLetters: 3,
              statementRequired: true,
              cvRequired: true,
              writingSampleRequired: true,
              portfolioRequired: false,
              interviewRequired: false,
            },
            deadlines: {
              fall: "December 15",
              spring: null,
              summer: null,
            },
            acceptanceRate: 0.04,
            tuition: 58000,
            duration: "5-6 years",
            website: "https://www.eecs.mit.edu/graduate/",
            facultyStrengths: ["AI", "Systems", "Networks", "Robotics"],
            researchAreas: ["Deep Learning", "Cybersecurity", "Quantum Computing"],
          },
          {
            id: createProgramId("Massachusetts Institute of Technology", "eecs-meng"),
            name: "Electrical Engineering and Computer Science",
            degree: "MEng",
            department: "School of Engineering",
            requirements: {
              gre: true,
              greRequired: false,
              grePreferred: true,
              greWaiver: true,
              toefl: true,
              toeflMinimum: 100,
              ielts: true,
              ieltsMinimum: 7.0,
              minimumGPA: 3.5,
              applicationFee: 75,
              recommendationLetters: 3,
              statementRequired: true,
              cvRequired: true,
              writingSampleRequired: false,
              portfolioRequired: false,
              interviewRequired: false,
            },
            deadlines: {
              fall: "December 15",
              spring: null,
              summer: null,
            },
            acceptanceRate: 0.10,
            tuition: 57000,
            duration: "1-1.5 years",
            website: "https://www.eecs.mit.edu/graduate/meng",
            facultyStrengths: ["AI", "Systems", "Robotics"],
            researchAreas: ["Machine Learning", "Computer Architecture", "Embedded Systems"],
          },
          {
            id: createProgramId("Massachusetts Institute of Technology", "data-science-ms"),
            name: "Data Science",
            degree: "MS",
            department: "Institute for Data, Systems, and Society",
            requirements: {
              gre: true,
              greRequired: true,
              grePreferred: false,
              greWaiver: false,
              toefl: true,
              toeflMinimum: 100,
              ielts: true,
              ieltsMinimum: 7.0,
              minimumGPA: 3.7,
              applicationFee: 75,
              recommendationLetters: 3,
              statementRequired: true,
              cvRequired: true,
              writingSampleRequired: false,
              portfolioRequired: false,
            },
            deadlines: {
              fall: "December 15",
              spring: null,
              summer: null,
            },
            acceptanceRate: 0.06,
            tuition: 58000,
            duration: "1-2 years",
            website: "https://www.mit.edu/data-science/graduate",
            facultyStrengths: ["Statistical Learning", "Big Data", "Applied ML"],
            researchAreas: ["Data Mining", "Computational Statistics", "Predictive Modeling"],
          },
        ],
        ranking: 2,
        website: "https://www.mit.edu",
        description: "MIT is a private research university in Cambridge, Massachusetts, often cited as one of the world's most prestigious universities, especially in science and engineering.",
        admissionStats: {
          applicants: 6500,
          admitted: 260,
          enrolled: 180,
          acceptanceRate: 0.04,
          averageGPA: 3.95,
          averageGRE: {
            verbal: 163,
            quantitative: 169,
            analytical: 4.6,
          },
        },
        imageUrl: "https://storage.googleapis.com/gradaid-images/mit.jpg",
      },
      {
        name: "University of California, Berkeley",
        location: {
          city: "Berkeley",
          state: "California",
          country: "USA",
          region: "West Coast",
        },
        programs: [
          {
            id: createProgramId("University of California, Berkeley", "cs-ms"),
            name: "Computer Science",
            degree: "MS",
            department: "College of Engineering",
            requirements: {
              gre: true,
              greRequired: false,
              grePreferred: true,
              greWaiver: true,
              toefl: true,
              toeflMinimum: 90,
              ielts: true,
              ieltsMinimum: 7.0,
              minimumGPA: 3.0,
              applicationFee: 120,
              recommendationLetters: 3,
              statementRequired: true,
              cvRequired: true,
              writingSampleRequired: false,
              portfolioRequired: false,
            },
            deadlines: {
              fall: "December 15",
              spring: null,
              summer: null,
            },
            tuition: 35000,
            duration: "1-2 years",
            website: "https://eecs.berkeley.edu/academics/graduate",
          },
          {
            id: createProgramId("University of California, Berkeley", "cs-phd"),
            name: "Computer Science",
            degree: "PhD",
            department: "College of Engineering",
            requirements: {
              gre: false,
              greRequired: false,
              grePreferred: false,
              greWaiver: false,
              toefl: true,
              toeflMinimum: 90,
              ielts: true,
              ieltsMinimum: 7.0,
              minimumGPA: 3.5,
              applicationFee: 120,
              recommendationLetters: 3,
              statementRequired: true,
              cvRequired: true,
              writingSampleRequired: true,
              portfolioRequired: false,
              interviewRequired: false,
            },
            deadlines: {
              fall: "December 15",
              spring: null,
              summer: null,
            },
            acceptanceRate: 0.05,
            tuition: 35000,
            duration: "5-6 years",
            website: "https://eecs.berkeley.edu/academics/graduate/phd",
            facultyStrengths: ["Theory", "Systems", "AI", "Graphics"],
            researchAreas: ["Machine Learning", "Algorithms", "Computer Architecture"],
          },
          {
            id: createProgramId("University of California, Berkeley", "data-science-ms"),
            name: "Data Science",
            degree: "MS",
            department: "School of Information",
            requirements: {
              gre: true,
              greRequired: false,
              grePreferred: true,
              greWaiver: true,
              toefl: true,
              toeflMinimum: 90,
              ielts: true,
              ieltsMinimum: 7.0,
              minimumGPA: 3.0,
              applicationFee: 120,
              recommendationLetters: 3,
              statementRequired: true,
              cvRequired: true,
              writingSampleRequired: false,
              portfolioRequired: false,
            },
            deadlines: {
              fall: "January 6",
              spring: null,
              summer: null,
            },
            tuition: 32000,
            duration: "1-2 years",
            website: "https://datascience.berkeley.edu/academics/masters",
            facultyStrengths: ["Statistical Methods", "Data Analysis", "Machine Learning"],
            researchAreas: ["Big Data", "Data Visualization", "Applied Data Science"],
          },
        ],
        ranking: 17,
website: "https://www.berkeley.edu",
        description: "UC Berkeley is a public research university and the flagship institution of the University of California system, known for its research output and high academic standards.",
        imageUrl: "https://storage.googleapis.com/gradaid-images/berkeley.jpg",
      },
      {
        name: "Carnegie Mellon University",
        location: {
          city: "Pittsburgh",
          state: "Pennsylvania",
          country: "USA",
          region: "East Coast",
        },
        programs: [
          {
            id: createProgramId("Carnegie Mellon University", "cs-ms"),
            name: "Computer Science",
            degree: "MS",
            department: "School of Computer Science",
            requirements: {
              gre: true,
              greRequired: true,
              grePreferred: false,
              greWaiver: false,
              toefl: true,
              toeflMinimum: 100,
              ielts: true,
              ieltsMinimum: 7.0,
              minimumGPA: 3.6,
              applicationFee: 100,
              recommendationLetters: 3,
              statementRequired: true,
              cvRequired: true,
              writingSampleRequired: false,
              portfolioRequired: false,
            },
            deadlines: {
              fall: "December 10",
              spring: null,
              summer: null,
              priority: null,
              funding: "December 10",
            },
            acceptanceRate: 0.09,
            tuition: 52000,
            duration: "1.5-2 years",
            website: "https://www.cs.cmu.edu/academics/masters",
            facultyStrengths: ["AI", "Machine Learning", "Robotics", "Human-Computer Interaction"],
            researchAreas: ["Deep Learning", "Computer Vision", "NLP"],
          },
          {
            id: createProgramId("Carnegie Mellon University", "cs-phd"),
            name: "Computer Science",
            degree: "PhD",
            department: "School of Computer Science",
            requirements: {
              gre: true,
              greRequired: true,
              grePreferred: false,
              greWaiver: false,
              toefl: true,
              toeflMinimum: 100,
              ielts: true,
              ieltsMinimum: 7.0,
              minimumGPA: 3.7,
              applicationFee: 100,
              recommendationLetters: 3,
              statementRequired: true,
              cvRequired: true,
              writingSampleRequired: true,
              portfolioRequired: false,
              interviewRequired: true,
            },
            deadlines: {
              fall: "December 10",
              spring: null,
              summer: null,
            },
            acceptanceRate: 0.06,
            tuition: 52000,
            duration: "5-6 years",
            website: "https://www.cs.cmu.edu/academics/doctoral",
            facultyStrengths: ["AI", "Machine Learning", "Programming Languages", "Systems"],
            researchAreas: ["Deep Learning", "Formal Methods", "Distributed Systems"],
          },
          {
            id: createProgramId("Carnegie Mellon University", "mlai-ms"),
            name: "Machine Learning and AI",
            degree: "MS",
            department: "School of Computer Science",
            requirements: {
              gre: true,
              greRequired: true,
              grePreferred: false,
              greWaiver: false,
              toefl: true,
              toeflMinimum: 100,
              ielts: true,
              ieltsMinimum: 7.0,
              minimumGPA: 3.6,
              applicationFee: 100,
              recommendationLetters: 3,
              statementRequired: true,
              cvRequired: true,
              writingSampleRequired: false,
              portfolioRequired: false,
            },
            deadlines: {
              fall: "December 10",
              spring: null,
              summer: null,
            },
            acceptanceRate: 0.07,
            tuition: 54000,
            duration: "1.5-2 years",
            website: "https://www.ml.cmu.edu/academics/ms-in-machine-learning.html",
            facultyStrengths: ["Machine Learning", "Deep Learning", "Statistical Methods", "Computer Vision"],
            researchAreas: ["Reinforcement Learning", "NLP", "Computational Biology"],
          },
        ],
        ranking: 21,
        website: "https://www.cmu.edu",
        description: "Carnegie Mellon University is a private research university in Pittsburgh, Pennsylvania, known for its world-class programs in computer science, robotics, and engineering.",
        admissionStats: {
          applicants: 5800,
          admitted: 522,
          enrolled: 250,
          acceptanceRate: 0.09,
          averageGPA: 3.85,
          averageGRE: {
            verbal: 162,
            quantitative: 169,
            analytical: 4.5,
          },
        },
        imageUrl: "https://storage.googleapis.com/gradaid-images/cmu.jpg",
      },
      {
        name: "Georgia Institute of Technology",
        location: {
          city: "Atlanta",
          state: "Georgia",
          country: "USA",
          region: "South",
        },
        programs: [
          {
            id: createProgramId("Georgia Institute of Technology", "cs-ms"),
            name: "Computer Science",
            degree: "MS",
            department: "College of Computing",
            requirements: {
              gre: true,
              greRequired: false,
              grePreferred: true,
              greWaiver: true,
              toefl: true,
              toeflMinimum: 90,
              ielts: true,
              ieltsMinimum: 7.0,
              minimumGPA: 3.0,
              applicationFee: 85,
              recommendationLetters: 2,
              statementRequired: true,
              cvRequired: true,
              writingSampleRequired: false,
              portfolioRequired: false,
            },
            deadlines: {
              fall: "February 1",
              spring: "August 1",
              summer: null,
            },
            acceptanceRate: 0.14,
            tuition: 28000,
            duration: "1-2 years",
            website: "https://www.cc.gatech.edu/ms-cs",
            facultyStrengths: ["Systems", "Machine Learning", "Cybersecurity"],
            researchAreas: ["AI", "High-Performance Computing", "Data Science"],
          },
          {
            id: createProgramId("Georgia Institute of Technology", "cs-phd"),
            name: "Computer Science",
            degree: "PhD",
            department: "College of Computing",
            requirements: {
              gre: true,
              greRequired: false,
              grePreferred: true,
              greWaiver: true,
              toefl: true,
              toeflMinimum: 90,
              ielts: true,
              ieltsMinimum: 7.0,
              minimumGPA: 3.5,
              applicationFee: 85,
              recommendationLetters: 3,
              statementRequired: true,
              cvRequired: true,
              writingSampleRequired: false,
              portfolioRequired: false,
              interviewRequired: true,
            },
            deadlines: {
              fall: "December 15",
              spring: "August 1",
              summer: null,
            },
            acceptanceRate: 0.12,
            tuition: 28000,
            duration: "5-6 years",
            website: "https://www.cc.gatech.edu/phd-cs",
            facultyStrengths: ["Systems", "Machine Learning", "Cybersecurity", "HCI"],
            researchAreas: ["AI", "High-Performance Computing", "Data Science", "Networks"],
          },
          {
            id: createProgramId("Georgia Institute of Technology", "cybersec-ms"),
            name: "Cybersecurity",
            degree: "MS",
            department: "College of Computing",
            requirements: {
              gre: true,
              greRequired: false,
              grePreferred: true,
              greWaiver: true,
              toefl: true,
              toeflMinimum: 90,
              ielts: true,
              ieltsMinimum: 7.0,
              minimumGPA: 3.0,
              applicationFee: 85,
              recommendationLetters: 2,
              statementRequired: true,
              cvRequired: true,
              writingSampleRequired: false,
              portfolioRequired: false,
            },
            deadlines: {
              fall: "February 1",
              spring: "August 1",
              summer: null,
            },
            acceptanceRate: 0.25,
            tuition: 26000,
            duration: "1-2 years",
            website: "https://www.cc.gatech.edu/ms-cybersecurity",
            facultyStrengths: ["Network Security", "Cryptography", "Systems Security"],
            researchAreas: ["Privacy", "Secure Computing", "Threat Analysis"],
          },
        ],
        ranking: 33,
        website: "https://www.gatech.edu",
        description: "Georgia Tech is a public research university in Atlanta, Georgia, renowned for its engineering, computing, and sciences programs.",
        admissionStats: {
          applicants: 8500,
          admitted: 1190,
          enrolled: 780,
          acceptanceRate: 0.14,
          averageGPA: 3.7,
          averageGRE: {
            verbal: 158,
            quantitative: 166,
            analytical: 4.2,
          },
        },
        imageUrl: "https://storage.googleapis.com/gradaid-images/gatech.jpg",
      },
      {
        name: "University of Washington",
        location: {
          city: "Seattle",
          state: "Washington",
          country: "USA",
          region: "West Coast",
        },
        programs: [
          {
            id: createProgramId("University of Washington", "cs-phd"),
            name: "Computer Science & Engineering",
            degree: "PhD",
            department: "Paul G. Allen School of Computer Science & Engineering",
            requirements: {
              gre: true,
              greRequired: false,
              grePreferred: true,
              greWaiver: true,
              toefl: true,
              toeflMinimum: 92,
              ielts: true,
              ieltsMinimum: 7.0,
              minimumGPA: 3.5,
              applicationFee: 85,
              recommendationLetters: 3,
              statementRequired: true,
              cvRequired: true,
              writingSampleRequired: false,
              portfolioRequired: false,
              interviewRequired: true,
            },
            deadlines: {
              fall: "December 15",
              spring: null,
              summer: null,
            },
            acceptanceRate: 0.08,
            tuition: 30000,
            duration: "5-6 years",
            website: "https://www.cs.washington.edu/academics/phd",
            facultyStrengths: ["Systems", "AI", "Programming Languages", "HCI"],
            researchAreas: ["Big Data", "Ubiquitous Computing", "Computational Biology"],
          },
          {
            id: createProgramId("University of Washington", "cs-ms"),
            name: "Computer Science & Engineering",
            degree: "MS",
            department: "Paul G. Allen School of Computer Science & Engineering",
            requirements: {
              gre: true,
              greRequired: false,
              grePreferred: true,
              greWaiver: true,
              toefl: true,
              toeflMinimum: 92,
              ielts: true,
              ieltsMinimum: 7.0,
              minimumGPA: 3.2,
              applicationFee: 85,
              recommendationLetters: 3,
              statementRequired: true,
              cvRequired: true,
              writingSampleRequired: false,
              portfolioRequired: false,
            },
            deadlines: {
              fall: "December 15",
              spring: null,
              summer: null,
            },
            acceptanceRate: 0.15,
            tuition: 30000,
            duration: "1-2 years",
            website: "https://www.cs.washington.edu/academics/masters",
            facultyStrengths: ["Systems", "AI", "Programming Languages"],
            researchAreas: ["Machine Learning", "Compilers", "Algorithms"],
          },
          {
            id: createProgramId("University of Washington", "data-science-ms"),
            name: "Data Science",
            degree: "MS",
            department: "Paul G. Allen School of Computer Science & Engineering",
            requirements: {
              gre: true,
              greRequired: false,
              grePreferred: true,
              greWaiver: true,
              toefl: true,
              toeflMinimum: 92,
              ielts: true,
              ieltsMinimum: 7.0,
              minimumGPA: 3.2,
              applicationFee: 85,
              recommendationLetters: 3,
              statementRequired: true,
              cvRequired: true,
              writingSampleRequired: false,
              portfolioRequired: false,
            },
            deadlines: {
              fall: "January 15",
              spring: null,
              summer: null,
            },
            acceptanceRate: 0.18,
            tuition: 30000,
            duration: "1-2 years",
            website: "https://www.cs.washington.edu/academics/datascience",
            facultyStrengths: ["Statistical Learning", "Data Mining", "Applied ML"],
            researchAreas: ["Big Data Analysis", "Visualization", "Data Engineering"],
          },
          {
            id: createProgramId("University of Washington", "computational-linguistics-ms"),
            name: "Computational Linguistics",
            degree: "MS",
            department: "Department of Linguistics",
            requirements: {
              gre: true,
              greRequired: false,
              grePreferred: true,
              greWaiver: true,
              toefl: true,
              toeflMinimum: 92,
              ielts: true,
              ieltsMinimum: 7.0,
              minimumGPA: 3.0,
              applicationFee: 85,
              recommendationLetters: 3,
              statementRequired: true,
              cvRequired: true,
              writingSampleRequired: false,
              portfolioRequired: false,
            },
            deadlines: {
              fall: "January 15",
              spring: null,
              summer: null,
            },
            acceptanceRate: 0.20,
            tuition: 28000,
            duration: "1-2 years",
            website: "https://www.compling.washington.edu/programs/ms",
            facultyStrengths: ["NLP", "Linguistics", "Machine Translation"],
            researchAreas: ["Semantic Analysis", "Speech Processing", "Language Models"],
          },
        ],
        ranking: 46,
        website: "https://www.washington.edu",
        description: "The University of Washington is a public research university in Seattle, Washington, known for its computer science, engineering, and medical research.",
        admissionStats: {
          applicants: 4200,
          admitted: 336,
          enrolled: 180,
          acceptanceRate: 0.08,
          averageGPA: 3.8,
          averageGRE: {
            verbal: 160,
            quantitative: 166,
            analytical: 4.3,
          },
        },
        imageUrl: "https://storage.googleapis.com/gradaid-images/uw.jpg",
      },
      {
        name: "University of Illinois at Urbana-Champaign",
        location: {
          city: "Urbana-Champaign",
          state: "Illinois",
          country: "USA",
          region: "Midwest",
        },
        programs: [
          {
            id: createProgramId("University of Illinois at Urbana-Champaign", "cs-ms"),
            name: "Computer Science",
            degree: "MS",
            department: "Department of Computer Science",
            requirements: {
              gre: true,
              greRequired: false,
              grePreferred: true,
              greWaiver: true,
              toefl: true,
              toeflMinimum: 103,
              ielts: true,
              ieltsMinimum: 7.5,
              minimumGPA: 3.2,
              applicationFee: 70,
              recommendationLetters: 3,
              statementRequired: true,
              cvRequired: true,
              writingSampleRequired: false,
              portfolioRequired: false,
            },
            deadlines: {
              fall: "December 15",
              spring: "September 15",
              summer: null,
            },
            acceptanceRate: 0.18,
            tuition: 27000,
            duration: "1.5-2 years",
            website: "https://cs.illinois.edu/academics/graduate/ms-program",
            facultyStrengths: ["Systems", "Data Science", "Programming Languages", "Architecture"],
            researchAreas: ["Distributed Systems", "Parallel Computing", "Compilers"],
          },
          {
            id: createProgramId("University of Illinois at Urbana-Champaign", "cs-phd"),
            name: "Computer Science",
            degree: "PhD",
            department: "Department of Computer Science",
            requirements: {
              gre: true,
              greRequired: false,
              grePreferred: true,
              greWaiver: true,
              toefl: true,
              toeflMinimum: 103,
              ielts: true,
              ieltsMinimum: 7.5,
              minimumGPA: 3.5,
              applicationFee: 70,
              recommendationLetters: 3,
              statementRequired: true,
              cvRequired: true,
              writingSampleRequired: true,
              portfolioRequired: false,
              interviewRequired: false,
            },
            deadlines: {
              fall: "December 15",
              spring: null,
              summer: null,
            },
            acceptanceRate: 0.14,
            tuition: 29000,
            duration: "5-6 years",
            website: "https://cs.illinois.edu/academics/graduate/phd-program",
            facultyStrengths: ["Systems", "Data Science", "Theory", "Security"],
            researchAreas: ["Machine Learning", "Scientific Computing", "Software Engineering"],
          },
          {
            id: createProgramId("University of Illinois at Urbana-Champaign", "mcs"),
            name: "Computer Science",
            degree: "MCS",
            department: "Department of Computer Science",
            requirements: {
              gre: true,
              greRequired: false,
              grePreferred: true,
              greWaiver: true,
              toefl: true,
              toeflMinimum: 103,
              ielts: true,
              ieltsMinimum: 7.5,
              minimumGPA: 3.0,
              applicationFee: 70,
              recommendationLetters: 3,
              statementRequired: true,
              cvRequired: true,
              writingSampleRequired: false,
              portfolioRequired: false,
            },
            deadlines: {
              fall: "January 15",
              spring: "October 15",
              summer: null,
            },
            acceptanceRate: 0.30,
            tuition: 21000,
            duration: "1-1.5 years",
            website: "https://cs.illinois.edu/academics/graduate/professional-mcs",
            facultyStrengths: ["Software Engineering", "Data Analytics", "Information Systems"],
            researchAreas: ["Web Technologies", "Cloud Computing", "App Development"],
          },
        ],
        ranking: 33,
        website: "https://illinois.edu",
        description: "The University of Illinois at Urbana-Champaign is a public land-grant research university, known for its engineering and computer science programs and home to the National Center for Supercomputing Applications.",
        admissionStats: {
          applicants: 4800,
          admitted: 864,
          enrolled: 310,
          acceptanceRate: 0.18,
          averageGPA: 3.75,
          averageGRE: {
            verbal: 158,
            quantitative: 167,
            analytical: 4.2,
          },
        },
        imageUrl: "https://storage.googleapis.com/gradaid-images/uiuc.jpg",
      },
      {
        name: "California Institute of Technology",
        location: {
          city: "Pasadena",
          state: "California",
          country: "USA",
          region: "West Coast",
        },
        programs: [
          {
            id: createProgramId("California Institute of Technology", "cs-phd"),
            name: "Computing and Mathematical Sciences",
            degree: "PhD",
            department: "Division of Engineering and Applied Science",
            requirements: {
              gre: true,
              greRequired: false,
              grePreferred: true,
              greWaiver: true,
              toefl: true,
              toeflMinimum: 100,
              ielts: true,
              ieltsMinimum: 7.0,
              minimumGPA: 3.8,
              applicationFee: 100,
              recommendationLetters: 3,
              statementRequired: true,
              cvRequired: true,
              writingSampleRequired: true,
              portfolioRequired: false,
              interviewRequired: true,
            },
            deadlines: {
              fall: "December 1",
              spring: null,
              summer: null,
            },
            acceptanceRate: 0.04,
            tuition: 58000,
            duration: "5-6 years",
            website: "https://cms.caltech.edu/academics/phd",
            facultyStrengths: ["Algorithms", "Theoretical CS", "Quantum Computing", "AI"],
            researchAreas: ["Machine Learning", "Scientific Computing", "Computational Biology"],
          },
          {
            id: createProgramId("California Institute of Technology", "cs-ms"),
            name: "Computing and Mathematical Sciences",
            degree: "MS",
            department: "Division of Engineering and Applied Science",
            requirements: {
              gre: true,
              greRequired: false,
              grePreferred: true,
              greWaiver: true,
              toefl: true,
              toeflMinimum: 100,
              ielts: true,
              ieltsMinimum: 7.0,
              minimumGPA: 3.5,
              applicationFee: 100,
              recommendationLetters: 3,
              statementRequired: true,
              cvRequired: true,
              writingSampleRequired: false,
              portfolioRequired: false,
            },
            deadlines: {
              fall: "December 1",
              spring: null,
              summer: null,
            },
            acceptanceRate: 0.08,
            tuition: 56000,
            duration: "1-2 years",
            website: "https://cms.caltech.edu/academics/masters",
            facultyStrengths: ["Algorithms", "Theoretical CS", "Mathematical Foundations"],
            researchAreas: ["Machine Learning", "Scientific Computing", "Optimization"],
          },
        ],
        ranking: 6,
        website: "https://www.caltech.edu",
        description: "Caltech is a world-renowned science and engineering institute with a 3:1 student-to-faculty ratio and an emphasis on research excellence in math, science, and engineering.",
        admissionStats: {
          applicants: 1200,
          admitted: 96,
          enrolled: 48,
          acceptanceRate: 0.08,
          averageGPA: 3.95,
          averageGRE: {
            verbal: 164,
            quantitative: 169,
            analytical: 4.5,
          },
        },
        imageUrl: "https://storage.googleapis.com/gradaid-images/caltech.jpg",
      },
      {
        name: "University of Michigan",
        location: {
          city: "Ann Arbor",
          state: "Michigan",
          country: "USA",
          region: "Midwest",
        },
        programs: [
          {
            id: createProgramId("University of Michigan", "cse-ms"),
            name: "Computer Science and Engineering",
            degree: "MS",
            department: "College of Engineering",
            requirements: {
              gre: true,
              greRequired: false,
              grePreferred: true,
              greWaiver: true,
              toefl: true,
              toeflMinimum: 84,
              ielts: true,
              ieltsMinimum: 6.5,
              minimumGPA: 3.2,
              applicationFee: 75,
              recommendationLetters: 3,
              statementRequired: true,
              cvRequired: true,
              writingSampleRequired: false,
              portfolioRequired: false,
            },
            deadlines: {
              fall: "January 15",
              spring: null,
              summer: null,
            },
            acceptanceRate: 0.25,
            tuition: 32000,
            duration: "1-2 years",
            website: "https://cse.engin.umich.edu/academics/graduate/masters-programs/",
            facultyStrengths: ["AI", "Systems", "Data Science", "Security"],
            researchAreas: ["Machine Learning", "Robotics", "Computer Architecture"],
          },
          {
            id: createProgramId("University of Michigan", "cse-phd"),
            name: "Computer Science and Engineering",
            degree: "PhD",
            department: "College of Engineering",
            requirements: {
              gre: true,
              greRequired: false,
              grePreferred: true,
              greWaiver: true,
              toefl: true,
              toeflMinimum: 84,
              ielts: true,
              ieltsMinimum: 6.5,
              minimumGPA: 3.5,
              applicationFee: 75,
              recommendationLetters: 3,
              statementRequired: true,
              cvRequired: true,
              writingSampleRequired: false,
              portfolioRequired: false,
              interviewRequired: false,
            },
            deadlines: {
              fall: "December 15",
              spring: null,
              summer: null,
            },
            acceptanceRate: 0.12,
            tuition: 32000,
            duration: "4-6 years",
            website: "https://cse.engin.umich.edu/academics/graduate/phd-program/",
            facultyStrengths: ["AI", "Systems", "Data Science", "Security", "HCI"],
            researchAreas: ["Machine Learning", "Robotics", "Cybersecurity", "Computer Architecture"],
          },
          {
            id: createProgramId("University of Michigan", "data-science-ms"),
            name: "Data Science",
            degree: "MS",
            department: "College of Engineering & College of LSA",
            requirements: {
              gre: true,
              greRequired: false,
              grePreferred: true,
              greWaiver: true,
              toefl: true,
              toeflMinimum: 84,
              ielts: true,
              ieltsMinimum: 6.5,
              minimumGPA: 3.2,
              applicationFee: 75,
              recommendationLetters: 3,
              statementRequired: true,
              cvRequired: true,
              writingSampleRequired: false,
              portfolioRequired: false,
            },
            deadlines: {
              fall: "January 15",
              spring: null,
              summer: null,
            },
            acceptanceRate: 0.30,
            tuition: 30000,
            duration: "1-2 years",
            website: "https://midas.umich.edu/data-science-masters/",
            facultyStrengths: ["Statistical Analysis", "Machine Learning", "Big Data"],
            researchAreas: ["Data Mining", "Data Visualization", "Predictive Analytics"],
          },
          {
            id: createProgramId("University of Michigan", "robotics-ms"),
            name: "Robotics",
            degree: "MS",
            department: "Michigan Robotics Institute",
            requirements: {
              gre: true,
              greRequired: false,
              grePreferred: true,
              greWaiver: true,
              toefl: true,
              toeflMinimum: 84,
              ielts: true,
              ieltsMinimum: 6.5,
              minimumGPA: 3.2,
              applicationFee: 75,
              recommendationLetters: 3,
              statementRequired: true,
              cvRequired: true,
              writingSampleRequired: false,
              portfolioRequired: false,
            },
            deadlines: {
              fall: "January 15",
              spring: null,
              summer: null,
            },
            acceptanceRate: 0.22,
            tuition: 33000,
            duration: "1.5-2 years",
            website: "https://robotics.umich.edu/academic-program/masters/",
            facultyStrengths: ["Autonomous Systems", "Computer Vision", "Robot Learning"],
            researchAreas: ["Self-driving Cars", "Manipulation", "Human-Robot Interaction"],
          },
        ],
        ranking: 21,
        website: "https://umich.edu",
        description: "The University of Michigan in Ann Arbor is a public research university with a comprehensive graduate program, particularly noted for engineering, computer science, and information sciences.",
        admissionStats: {
          applicants: 5200,
          admitted: 1300,
          enrolled: 650,
          acceptanceRate: 0.25,
          averageGPA: 3.7,
          averageGRE: {
            verbal: 159,
            quantitative: 165,
            analytical: 4.2,
          },
        },
        imageUrl: "https://storage.googleapis.com/gradaid-images/umich.jpg",
      },
      {
        name: "Cornell University",
        location: {
          city: "Ithaca",
          state: "New York",
          country: "USA",
          region: "East Coast",
        },
        programs: [
          {
            id: createProgramId("Cornell University", "cs-ms"),
            name: "Computer Science",
            degree: "MS",
            department: "Department of Computer Science",
            requirements: {
              gre: true,
              greRequired: false,
              grePreferred: true,
              greWaiver: true,
              toefl: true,
              toeflMinimum: 100,
              ielts: true,
              ieltsMinimum: 7.0,
              minimumGPA: 3.3,
              applicationFee: 105,
              recommendationLetters: 3,
              statementRequired: true,
              cvRequired: true,
              writingSampleRequired: false,
              portfolioRequired: false,
            },
            deadlines: {
              fall: "December 15",
              spring: null,
              summer: null,
            },
            acceptanceRate: 0.15,
            tuition: 48000,
            duration: "1-2 years",
            website: "https://www.cs.cornell.edu/ms",
            facultyStrengths: ["AI", "Programming Languages", "Systems", "Theory"],
            researchAreas: ["Machine Learning", "Algorithms", "Distributed Computing"],
          },
          {
            id: createProgramId("Cornell University", "cs-phd"),
            name: "Computer Science",
            degree: "PhD",
            department: "Department of Computer Science",
            requirements: {
              gre: false,
              greRequired: false,
              grePreferred: false,
              greWaiver: false,
              toefl: true,
              toeflMinimum: 100,
              ielts: true,
              ieltsMinimum: 7.0,
              minimumGPA: 3.5,
              applicationFee: 105,
              recommendationLetters: 3,
              statementRequired: true,
              cvRequired: true,
              writingSampleRequired: true,
              portfolioRequired: false,
              interviewRequired: false,
            },
            deadlines: {
              fall: "December 1",
              spring: null,
              summer: null,
            },
            acceptanceRate: 0.09,
            tuition: 48000,
            duration: "5-6 years",
            website: "https://www.cs.cornell.edu/phd",
            facultyStrengths: ["AI", "Theory", "Programming Languages", "Systems"],
            researchAreas: ["NLP", "Computer Vision", "Algorithms", "Distributed Systems"],
          },
          {
            id: createProgramId("Cornell University", "cs-meng"),
            name: "Computer Science",
            degree: "MEng",
            department: "Department of Computer Science",
            requirements: {
              gre: true,
              greRequired: false,
              grePreferred: true,
              greWaiver: true,
              toefl: true,
              toeflMinimum: 100,
              ielts: true,
              ieltsMinimum: 7.0,
              minimumGPA: 3.0,
              applicationFee: 105,
              recommendationLetters: 2,
              statementRequired: true,
              cvRequired: true,
              writingSampleRequired: false,
              portfolioRequired: false,
            },
            deadlines: {
              fall: "January 15",
              spring: "October 1",
              summer: null,
            },
            acceptanceRate: 0.25,
            tuition: 46000,
            duration: "1-1.5 years",
            website: "https://www.cs.cornell.edu/meng",
            facultyStrengths: ["Software Engineering", "Data Science", "Systems"],
            researchAreas: ["Machine Learning Applications", "Software Development", "Data Analytics"],
          },
          {
            id: createProgramId("Cornell University", "info-science-ms"),
            name: "Information Science",
            degree: "MS",
            department: "Department of Information Science",
            requirements: {
              gre: true,
              greRequired: false,
              grePreferred: true,
              greWaiver: true,
              toefl: true,
              toeflMinimum: 100,
              ielts: true,
              ieltsMinimum: 7.0,
              minimumGPA: 3.0,
              applicationFee: 105,
              recommendationLetters: 3,
              statementRequired: true,
              cvRequired: true,
              writingSampleRequired: false,
              portfolioRequired: false,
            },
            deadlines: {
              fall: "January 15",
              spring: null,
              summer: null,
            },
            acceptanceRate: 0.22,
            tuition: 46000,
            duration: "1.5-2 years",
            website: "https://infosci.cornell.edu/ms",
            facultyStrengths: ["HCI", "Social Computing", "Data Science"],
            researchAreas: ["Digital Ethics", "Information Systems", "UX Research"],
          },
        ],
        ranking: 11,
        website: "https://www.cornell.edu",
        description: "Cornell University is a private Ivy League university with strong research output in computer science, information science, and engineering, particularly known for interdisciplinary work.",
        admissionStats: {
          applicants: 4000,
          admitted: 600,
          enrolled: 280,
          acceptanceRate: 0.15,
          averageGPA: 3.8,
          averageGRE: {
            verbal: 162,
            quantitative: 167,
            analytical: 4.3,
          },
        },
        imageUrl: "https://storage.googleapis.com/gradaid-images/cornell.jpg",
      },
      {
        name: "Princeton University",
        location: {
          city: "Princeton",
          state: "New Jersey",
          country: "USA",
          region: "East Coast",
        },
        programs: [
          {
            id: createProgramId("Princeton University", "cs-phd"),
            name: "Computer Science",
            degree: "PhD",
            department: "Department of Computer Science",
            requirements: {
              gre: false,
              greRequired: false,
              grePreferred: false,
              greWaiver: false,
              toefl: true,
              toeflMinimum: 100,
              ielts: true,
              ieltsMinimum: 7.0,
              minimumGPA: 3.5,
              applicationFee: 95,
              recommendationLetters: 3,
              statementRequired: true,
              cvRequired: true,
              writingSampleRequired: true,
              portfolioRequired: false,
              interviewRequired: false,
            },
            deadlines: {
              fall: "December 1",
              spring: null,
              summer: null,
            },
            acceptanceRate: 0.05,
            tuition: 54000,
            duration: "5-6 years",
            website: "https://www.cs.princeton.edu/graduate/phd",
            facultyStrengths: ["Algorithms", "AI", "Systems", "Theory"],
            researchAreas: ["Machine Learning", "Security", "Computational Biology"],
          },
          {
            id: createProgramId("Princeton University", "cs-mse"),
            name: "Computer Science",
            degree: "MSE",
            department: "Department of Computer Science",
            requirements: {
              gre: true,
              greRequired: false,
              grePreferred: true,
              greWaiver: true,
              toefl: true,
              toeflMinimum: 100,
              ielts: true,
              ieltsMinimum: 7.0,
              minimumGPA: 3.5,
              applicationFee: 95,
              recommendationLetters: 3,
              statementRequired: true,
              cvRequired: true,
              writingSampleRequired: false,
              portfolioRequired: false,
            },
            deadlines: {
              fall: "December 15",
              spring: null,
              summer: null,
            },
            acceptanceRate: 0.09,
            tuition: 54000,
            duration: "1-2 years",
            website: "https://www.cs.princeton.edu/graduate/masters",
            facultyStrengths: ["Theory", "AI", "Programming Languages"],
            researchAreas: ["Algorithms", "Machine Learning", "Formal Methods"],
          },
          {
            id: createProgramId("Princeton University", "finance-mfin"),
            name: "Financial Engineering",
            degree: "MFin",
            department: "Department of Operations Research & Financial Engineering",
            requirements: {
              gre: true,
              greRequired: true,
              grePreferred: false,
              greWaiver: false,
              toefl: true,
              toeflMinimum: 100,
              ielts: true,
              ieltsMinimum: 7.0,
              minimumGPA: 3.5,
              applicationFee: 95,
              recommendationLetters: 3,
              statementRequired: true,
              cvRequired: true,
              writingSampleRequired: false,
              portfolioRequired: false,
            },
            deadlines: {
              fall: "January 5",
              spring: null,
              summer: null,
            },
            acceptanceRate: 0.12,
            tuition: 56000,
            duration: "2 years",
            website: "https://orfe.princeton.edu/graduate/financial-engineering",
            facultyStrengths: ["Quantitative Finance", "Stochastic Modeling", "Optimization"],
            researchAreas: ["Financial Mathematics", "Risk Management", "Algorithmic Trading"],
          },
        ],
        ranking: 1,
        website: "https://www.princeton.edu",
        description: "Princeton University is a prestigious Ivy League research university with comprehensive graduate programs, particularly noted for computer science, mathematics, and engineering.",
        admissionStats: {
          applicants: 2800,
          admitted: 224,
          enrolled: 85,
          acceptanceRate: 0.08,
          averageGPA: 3.9,
          averageGRE: {
            verbal: 164,
            quantitative: 168,
            analytical: 4.5,
          },
        },
        imageUrl: "https://storage.googleapis.com/gradaid-images/princeton.jpg",
      },
      {
        name: "Harvard University",
        location: {
          city: "Cambridge",
          state: "Massachusetts",
          country: "USA",
          region: "East Coast",
        },
        programs: [
          {
            id: createProgramId("Harvard University", "cs-phd"),
            name: "Computer Science",
            degree: "PhD",
            department: "School of Engineering and Applied Sciences",
            requirements: {
              gre: false,
              greRequired: false,
              grePreferred: false,
              greWaiver: false,
              toefl: true,
              toeflMinimum: 100,
              ielts: true,
              ieltsMinimum: 7.0,
              minimumGPA: 3.7,
              applicationFee: 105,
              recommendationLetters: 3,
              statementRequired: true,
              cvRequired: true,
              writingSampleRequired: true,
              portfolioRequired: false,
              interviewRequired: false,
            },
            deadlines: {
              fall: "December 15",
              spring: null,
              summer: null,
            },
            acceptanceRate: 0.05,
            tuition: 54000,
            duration: "5-6 years",
            website: "https://www.seas.harvard.edu/computer-science/graduate-programs",
            facultyStrengths: ["AI", "Theory", "Systems", "Computational Biology"],
            researchAreas: ["Machine Learning", "Algorithms", "Computational Science"],
          },
          {
            id: createProgramId("Harvard University", "cs-ms"),
            name: "Computational Science and Engineering",
            degree: "MS",
            department: "School of Engineering and Applied Sciences",
            requirements: {
              gre: true,
              greRequired: false,
              grePreferred: true,
              greWaiver: true,
              toefl: true,
              toeflMinimum: 100,
              ielts: true,
              ieltsMinimum: 7.0,
              minimumGPA: 3.5,
              applicationFee: 105,
              recommendationLetters: 3,
              statementRequired: true,
              cvRequired: true,
              writingSampleRequired: false,
              portfolioRequired: false,
            },
            deadlines: {
              fall: "December 15",
              spring: null,
              summer: null,
            },
            acceptanceRate: 0.10,
            tuition: 52000,
            duration: "1.5-2 years",
            website: "https://www.seas.harvard.edu/computational-science-engineering/master-science-cse",
            facultyStrengths: ["Data Science", "Computational Modeling", "AI"],
            researchAreas: ["Scientific Computing", "Computational Science", "Data Analytics"],
          },
        ],
        ranking: 3,
        website: "https://www.harvard.edu",
        description: "Harvard University is a private Ivy League research university in Cambridge, Massachusetts, established in 1636. It is the oldest institution of higher learning in the United States and among the most prestigious in the world.",
        admissionStats: {
          applicants: 6800,
          admitted: 680,
          enrolled: 300,
          acceptanceRate: 0.10,
          averageGPA: 3.9,
          averageGRE: {
            verbal: 165,
            quantitative: 167,
            analytical: 4.7,
          },
        },
        imageUrl: "https://storage.googleapis.com/gradaid-images/harvard.jpg",
      },
      {
        name: "Boston University",
        location: {
          city: "Boston",
          state: "Massachusetts",
          country: "USA",
          region: "East Coast",
        },
        programs: [
          {
            id: createProgramId("Boston University", "cs-ms"),
            name: "Computer Science",
            degree: "MS",
            department: "Department of Computer Science",
            requirements: {
              gre: true,
              greRequired: false,
              grePreferred: true,
              greWaiver: true,
              toefl: true,
              toeflMinimum: 95,
              ielts: true,
              ieltsMinimum: 7.0,
              minimumGPA: 3.0,
              applicationFee: 95,
              recommendationLetters: 3,
              statementRequired: true,
              cvRequired: true,
              writingSampleRequired: false,
              portfolioRequired: false,
            },
            deadlines: {
              fall: "January 15",
              spring: "September 15",
              summer: null,
            },
            acceptanceRate: 0.32,
            tuition: 48000,
            duration: "1.5-2 years",
            website: "https://www.bu.edu/cs/masters/",
            facultyStrengths: ["Data Science", "Systems", "Security", "AI"],
            researchAreas: ["Machine Learning", "Networking", "Software Engineering"],
          },
          {
            id: createProgramId("Boston University", "cs-phd"),
            name: "Computer Science",
            degree: "PhD",
            department: "Department of Computer Science",
            requirements: {
              gre: true,
              greRequired: false,
              grePreferred: true,
              greWaiver: true,
              toefl: true,
              toeflMinimum: 95,
              ielts: true,
              ieltsMinimum: 7.0,
              minimumGPA: 3.5,
              applicationFee: 95,
              recommendationLetters: 3,
              statementRequired: true,
              cvRequired: true,
              writingSampleRequired: true,
              portfolioRequired: false,
              interviewRequired: false,
            },
            deadlines: {
              fall: "December 15",
              spring: null,
              summer: null,
            },
            acceptanceRate: 0.18,
            tuition: 48000,
            duration: "5-6 years",
            website: "https://www.bu.edu/cs/phd/",
            facultyStrengths: ["Data Science", "AI", "Systems", "Theory"],
            researchAreas: ["Machine Learning", "Computer Vision", "Distributed Systems"],
          },
        ],
        ranking: 41,
        website: "https://www.bu.edu",
        description: "Boston University is a private research university in Boston, Massachusetts, with a diverse and international student body. It offers comprehensive graduate programs across various disciplines.",
        admissionStats: {
          applicants: 3500,
          admitted: 1120,
          enrolled: 450,
          acceptanceRate: 0.32,
          averageGPA: 3.6,
          averageGRE: {
            verbal: 157,
            quantitative: 163,
            analytical: 4.0,
          },
        },
        imageUrl: "https://storage.googleapis.com/gradaid-images/bu.jpg",
      },
      {
        name: "Northeastern University",
        location: {
          city: "Boston",
          state: "Massachusetts",
          country: "USA",
          region: "East Coast",
        },
        programs: [
          {
            id: createProgramId("Northeastern University", "cs-ms"),
            name: "Computer Science",
            degree: "MS",
            department: "Khoury College of Computer Sciences",
            requirements: {
              gre: true,
              greRequired: false,
              grePreferred: true,
              greWaiver: true,
              toefl: true,
              toeflMinimum: 100,
              ielts: true,
              ieltsMinimum: 7.5,
              minimumGPA: 3.0,
              applicationFee: 75,
              recommendationLetters: 3,
              statementRequired: true,
              cvRequired: true,
              writingSampleRequired: false,
              portfolioRequired: false,
            },
            deadlines: {
              fall: "March 15",
              spring: "September 15",
              summer: "January 15",
            },
            acceptanceRate: 0.40,
            tuition: 42000,
            duration: "1-2 years",
            website: "https://www.khoury.northeastern.edu/programs/computer-science-ms/",
            facultyStrengths: ["AI", "Data Science", "Cybersecurity", "Software Engineering"],
            researchAreas: ["Machine Learning", "Network Security", "Human-Computer Interaction"],
          },
          {
            id: createProgramId("Northeastern University", "cs-align-ms"),
            name: "Computer Science ALIGN",
            degree: "MS",
            department: "Khoury College of Computer Sciences",
            requirements: {
              gre: true,
              greRequired: false,
              grePreferred: false,
              greWaiver: true,
              toefl: true,
              toeflMinimum: 100,
              ielts: true,
              ieltsMinimum: 7.5,
              minimumGPA: 3.0,
              applicationFee: 75,
              recommendationLetters: 2,
              statementRequired: true,
              cvRequired: true,
              writingSampleRequired: false,
              portfolioRequired: false,
            },
            deadlines: {
              fall: "May 15",
              spring: "November 15",
              summer: "March 15",
            },
            acceptanceRate: 0.65,
            tuition: 52000,
            duration: "2-2.5 years",
            website: "https://www.khoury.northeastern.edu/programs/align-masters-of-computer-science/",
            facultyStrengths: ["Software Engineering", "Data Analytics", "AI"],
            researchAreas: ["Software Development", "Data Science", "AI Applications"],
          },
          {
            id: createProgramId("Northeastern University", "cs-phd"),
            name: "Computer Science",
            degree: "PhD",
            department: "Khoury College of Computer Sciences",
            requirements: {
              gre: true,
              greRequired: false,
              grePreferred: true,
              greWaiver: true,
              toefl: true,
              toeflMinimum: 100,
              ielts: true,
              ieltsMinimum: 7.5,
              minimumGPA: 3.5,
              applicationFee: 75,
              recommendationLetters: 3,
              statementRequired: true,
              cvRequired: true,
              writingSampleRequired: true,
              portfolioRequired: false,
              interviewRequired: false,
            },
            deadlines: {
              fall: "December 15",
              spring: null,
              summer: null,
            },
            acceptanceRate: 0.15,
            tuition: 42000,
            duration: "4-6 years",
            website: "https://www.khoury.northeastern.edu/programs/computer-science-phd/",
            facultyStrengths: ["AI", "Networks", "Programming Languages", "Data Science"],
            researchAreas: ["Machine Learning", "Security", "Software Engineering"],
          },
        ],
        ranking: 54,
        website: "https://www.northeastern.edu",
        description: "Northeastern University is a private research university with its main campus in Boston. The university is known for its cooperative education program, which integrates classroom study with professional experience.",
        admissionStats: {
          applicants: 4200,
          admitted: 1680,
          enrolled: 720,
          acceptanceRate: 0.40,
          averageGPA: 3.5,
          averageGRE: {
            verbal: 155,
            quantitative: 162,
            analytical: 4.0,
          },
        },
        imageUrl: "https://storage.googleapis.com/gradaid-images/northeastern.jpg",
      },
      {
        name: "Tufts University",
        location: {
          city: "Medford",
          state: "Massachusetts",
          country: "USA",
          region: "East Coast",
        },
        programs: [
          {
            id: createProgramId("Tufts University", "cs-ms"),
            name: "Computer Science",
            degree: "MS",
            department: "Department of Computer Science",
            requirements: {
              gre: true,
              greRequired: false,
              grePreferred: true,
              greWaiver: true,
              toefl: true,
              toeflMinimum: 90,
              ielts: true,
              ieltsMinimum: 6.5,
              minimumGPA: 3.0,
              applicationFee: 85,
              recommendationLetters: 3,
              statementRequired: true,
              cvRequired: true,
              writingSampleRequired: false,
              portfolioRequired: false,
            },
            deadlines: {
              fall: "January 15",
              spring: "October 1",
              summer: null,
            },
            acceptanceRate: 0.35,
            tuition: 48000,
            duration: "1-2 years",
            website: "https://engineering.tufts.edu/cs/graduate/masters",
            facultyStrengths: ["AI", "HCI", "Data Science", "Robotics"],
            researchAreas: ["Machine Learning", "Cognitive Science", "Graphics"],
          },
          {
            id: createProgramId("Tufts University", "cs-phd"),
            name: "Computer Science",
            degree: "PhD",
            department: "Department of Computer Science",
            requirements: {
              gre: true,
              greRequired: false,
              grePreferred: true,
              greWaiver: true,
              toefl: true,
              toeflMinimum: 90,
              ielts: true,
              ieltsMinimum: 6.5,
              minimumGPA: 3.5,
              applicationFee: 85,
              recommendationLetters: 3,
              statementRequired: true,
              cvRequired: true,
              writingSampleRequired: false,
              portfolioRequired: false,
              interviewRequired: false,
            },
            deadlines: {
              fall: "December 15",
              spring: null,
              summer: null,
            },
            acceptanceRate: 0.18,
            tuition: 48000,
            duration: "4-6 years",
            website: "https://engineering.tufts.edu/cs/graduate/phd",
            facultyStrengths: ["AI", "Robotics", "HCI", "Computational Biology"],
            researchAreas: ["Machine Learning", "Cognitive Science", "Human-Robot Interaction"],
          },
        ],
        ranking: 37,
        website: "https://www.tufts.edu",
        description: "Tufts University is a private research university on the border of Medford and Somerville, Massachusetts. It emphasizes active citizenship and public service in its education.",
        admissionStats: {
          applicants: 2800,
          admitted: 980,
          enrolled: 380,
          acceptanceRate: 0.35,
          averageGPA: 3.6,
          averageGRE: {
            verbal: 157,
            quantitative: 162,
            analytical: 4.2,
          },
        },
        imageUrl: "https://storage.googleapis.com/gradaid-images/tufts.jpg",
      }
    ];

    // Insert universities
    for (const university of universities) {
      await ctx.db.insert("universities", university);
    }

    return { 
      status: "initialized", 
      count: universities.length 
    };
  },
});
