import { internalMutation } from "./_generated/server";

// Default export that safely seeds the database
export default internalMutation({
  handler: async (ctx) => {
    console.log("Initializing database with seed data...");

    // Seed universities data
    const universities = [
      {
        name: "Stanford University",
        location: {
          city: "Stanford",
          state: "California",
          country: "USA",
          region: "West Coast",
        },
        programs: [
          {
            id: "cs-ms",
            name: "Computer Science",
            degree: "Master of Science",
            department: "School of Engineering",
            requirements: {
              gre: true,
              greRequired: true,
              grePreferred: false,
              greWaiver: false,
              toefl: true,
              toeflMinimum: 100,
              ielts: true,
              ieltsMinimum: 7.0,
              minimumGPA: 3.5,
              applicationFee: 125,
              recommendationLetters: 3,
              statementRequired: true,
              cvRequired: true,
              writingSampleRequired: false,
              portfolioRequired: false,
            },
            deadlines: {
              fall: "December 1",
              spring: null,
              summer: null,
              priority: "November 15",
              funding: "December 1",
            },
            acceptanceRate: 0.05,
            tuition: 55000,
            duration: "1-2 years",
            website: "https://cs.stanford.edu/academics/masters",
            facultyStrengths: ["AI", "Systems", "Theory", "HCI"],
            researchAreas: ["Machine Learning", "Computer Vision", "Robotics"],
          },
          {
            id: "cs-phd",
            name: "Computer Science",
            degree: "PhD",
            department: "School of Engineering",
            requirements: {
              gre: true,
              greRequired: true,
              grePreferred: false,
              greWaiver: false,
              toefl: true,
              toeflMinimum: 100,
              ielts: true,
              ieltsMinimum: 7.0,
              minimumGPA: 3.7,
              applicationFee: 125,
              recommendationLetters: 3,
              statementRequired: true,
              cvRequired: true,
              writingSampleRequired: true,
              portfolioRequired: false,
              interviewRequired: true,
            },
            deadlines: {
              fall: "December 1",
              spring: null,
              summer: null,
            },
            acceptanceRate: 0.03,
            tuition: 55000,
            duration: "5-6 years",
            website: "https://cs.stanford.edu/academics/phd",
            facultyStrengths: ["AI", "Systems", "Theory", "HCI"],
            researchAreas: ["Machine Learning", "Computer Vision", "Robotics"],
          }
        ],
        ranking: 2,
        website: "https://www.stanford.edu",
        description: "Stanford University is a private research university in Stanford, California, known for its academic strength, proximity to Silicon Valley, and ranking as one of the world's top universities.",
        admissionStats: {
          applicants: 7000,
          admitted: 350,
          enrolled: 200,
          acceptanceRate: 0.05,
          averageGPA: 3.9,
          averageGRE: {
            verbal: 165,
            quantitative: 168,
            analytical: 4.5,
          },
        },
        imageUrl: "https://storage.googleapis.com/gradaid-images/stanford.jpg",
      },
      {
        name: "Massachusetts Institute of Technology",
        location: {
          city: "Cambridge",
          state: "Massachusetts",
          country: "USA",
          region: "East Coast",
        },
        programs: [
          {
            id: "eecs-phd",
            name: "Electrical Engineering and Computer Science",
            degree: "PhD",
            department: "School of Engineering",
            requirements: {
              gre: true,
              greRequired: true,
              grePreferred: false,
              greWaiver: false,
              toefl: true,
              toeflMinimum: 100,
              ielts: true,
              ieltsMinimum: 7.0,
              minimumGPA: 3.7,
              applicationFee: 75,
              recommendationLetters: 3,
              statementRequired: true,
              cvRequired: true,
              writingSampleRequired: true,
              portfolioRequired: false,
              interviewRequired: false,
            },
            deadlines: {
              fall: "December 15",
              spring: null,
              summer: null,
            },
            acceptanceRate: 0.04,
            tuition: 58000,
            duration: "5-6 years",
            website: "https://www.eecs.mit.edu/graduate/",
            facultyStrengths: ["AI", "Systems", "Networks", "Robotics"],
            researchAreas: ["Deep Learning", "Cybersecurity", "Quantum Computing"],
          }
        ],
        ranking: 1,
        website: "https://www.mit.edu",
        description: "MIT is a private research university in Cambridge, Massachusetts, often cited as one of the world's most prestigious universities, especially in science and engineering.",
        admissionStats: {
          applicants: 6500,
          admitted: 260,
          enrolled: 180,
          acceptanceRate: 0.04,
          averageGPA: 3.95,
          averageGRE: {
            verbal: 163,
            quantitative: 169,
            analytical: 4.6,
          },
        },
        imageUrl: "https://storage.googleapis.com/gradaid-images/mit.jpg",
      },
      {
        name: "University of California, Berkeley",
        location: {
          city: "Berkeley",
          state: "California",
          country: "USA",
          region: "West Coast",
        },
        programs: [
          {
            id: "cs-ms",
            name: "Computer Science",
            degree: "Master of Science",
            department: "College of Engineering",
            requirements: {
              gre: true,
              greRequired: false,
              grePreferred: true,
              greWaiver: true,
              toefl: true,
              toeflMinimum: 90,
              ielts: true,
              ieltsMinimum: 7.0,
              minimumGPA: 3.0,
              applicationFee: 120,
              recommendationLetters: 3,
              statementRequired: true,
              cvRequired: true,
              writingSampleRequired: false,
              portfolioRequired: false,
            },
            deadlines: {
              fall: "December 15",
              spring: null,
              summer: null,
            },
            tuition: 35000,
            duration: "1-2 years",
            website: "https://eecs.berkeley.edu/academics/graduate",
          }
        ],
        ranking: 4,
        website: "https://www.berkeley.edu",
        description: "UC Berkeley is a public research university and the flagship institution of the University of California system, known for its research output and high academic standards.",
        imageUrl: "https://storage.googleapis.com/gradaid-images/berkeley.jpg",
      },
      {
        name: "Carnegie Mellon University",
        location: {
          city: "Pittsburgh",
          state: "Pennsylvania",
          country: "USA",
          region: "East Coast",
        },
        programs: [
          {
            id: "cs-ms",
            name: "Computer Science",
            degree: "Master of Science",
            department: "School of Computer Science",
            requirements: {
              gre: true,
              greRequired: true,
              grePreferred: false,
              greWaiver: false,
              toefl: true,
              toeflMinimum: 100,
              ielts: true,
              ieltsMinimum: 7.0,
              minimumGPA: 3.6,
              applicationFee: 100,
              recommendationLetters: 3,
              statementRequired: true,
              cvRequired: true,
              writingSampleRequired: false,
              portfolioRequired: false,
            },
            deadlines: {
              fall: "December 10",
              spring: null,
              summer: null,
              priority: null,
              funding: "December 10",
            },
            acceptanceRate: 0.09,
            tuition: 52000,
            duration: "1.5-2 years",
            website: "https://www.cs.cmu.edu/academics/masters",
            facultyStrengths: ["AI", "Machine Learning", "Robotics", "Human-Computer Interaction"],
            researchAreas: ["Deep Learning", "Computer Vision", "NLP"],
          }
        ],
        ranking: 3,
        website: "https://www.cmu.edu",
        description: "Carnegie Mellon University is a private research university in Pittsburgh, Pennsylvania, known for its world-class programs in computer science, robotics, and engineering.",
        admissionStats: {
          applicants: 5800,
          admitted: 522,
          enrolled: 250,
          acceptanceRate: 0.09,
          averageGPA: 3.85,
          averageGRE: {
            verbal: 162,
            quantitative: 169,
            analytical: 4.5,
          },
        },
        imageUrl: "https://storage.googleapis.com/gradaid-images/cmu.jpg",
      },
      {
        name: "Georgia Institute of Technology",
        location: {
          city: "Atlanta",
          state: "Georgia",
          country: "USA",
          region: "South",
        },
        programs: [
          {
            id: "cs-ms",
            name: "Computer Science",
            degree: "Master of Science",
            department: "College of Computing",
            requirements: {
              gre: true,
              greRequired: false,
              grePreferred: true,
              greWaiver: true,
              toefl: true,
              toeflMinimum: 90,
              ielts: true,
              ieltsMinimum: 7.0,
              minimumGPA: 3.0,
              applicationFee: 85,
              recommendationLetters: 2,
              statementRequired: true,
              cvRequired: true,
              writingSampleRequired: false,
              portfolioRequired: false,
            },
            deadlines: {
              fall: "February 1",
              spring: "August 1",
              summer: null,
            },
            acceptanceRate: 0.14,
            tuition: 28000,
            duration: "1-2 years",
            website: "https://www.cc.gatech.edu/ms-cs",
            facultyStrengths: ["Systems", "Machine Learning", "Cybersecurity"],
            researchAreas: ["AI", "High-Performance Computing", "Data Science"],
          }
        ],
        ranking: 8,
        website: "https://www.gatech.edu",
        description: "Georgia Tech is a public research university in Atlanta, Georgia, renowned for its engineering, computing, and sciences programs.",
        admissionStats: {
          applicants: 8500,
          admitted: 1190,
          enrolled: 780,
          acceptanceRate: 0.14,
          averageGPA: 3.7,
          averageGRE: {
            verbal: 158,
            quantitative: 166,
            analytical: 4.2,
          },
        },
        imageUrl: "https://storage.googleapis.com/gradaid-images/gatech.jpg",
      },
      {
        name: "University of Washington",
        location: {
          city: "Seattle",
          state: "Washington",
          country: "USA",
          region: "West Coast",
        },
        programs: [
          {
            id: "cs-phd",
            name: "Computer Science & Engineering",
            degree: "PhD",
            department: "Paul G. Allen School of Computer Science & Engineering",
            requirements: {
              gre: true,
              greRequired: false,
              grePreferred: true,
              greWaiver: true,
              toefl: true,
              toeflMinimum: 92,
              ielts: true,
              ieltsMinimum: 7.0,
              minimumGPA: 3.5,
              applicationFee: 85,
              recommendationLetters: 3,
              statementRequired: true,
              cvRequired: true,
              writingSampleRequired: false,
              portfolioRequired: false,
              interviewRequired: true,
            },
            deadlines: {
              fall: "December 15",
              spring: null,
              summer: null,
            },
            acceptanceRate: 0.08,
            tuition: 30000,
            duration: "5-6 years",
            website: "https://www.cs.washington.edu/academics/phd",
            facultyStrengths: ["Systems", "AI", "Programming Languages", "HCI"],
            researchAreas: ["Big Data", "Ubiquitous Computing", "Computational Biology"],
          }
        ],
        ranking: 6,
        website: "https://www.washington.edu",
        description: "The University of Washington is a public research university in Seattle, Washington, known for its computer science, engineering, and medical research.",
        admissionStats: {
          applicants: 4200,
          admitted: 336,
          enrolled: 180,
          acceptanceRate: 0.08,
          averageGPA: 3.8,
          averageGRE: {
            verbal: 160,
            quantitative: 166,
            analytical: 4.3,
          },
        },
        imageUrl: "https://storage.googleapis.com/gradaid-images/uw.jpg",
      }
    ];

    // Insert universities
    for (const university of universities) {
      await ctx.db.insert("universities", university);
    }

    return { 
      status: "initialized", 
      count: universities.length 
    };
  },
});
