import countryList from 'react-select-country-list';

export const degreeOptions = [
  { id: 1, value: 'secondary', label: 'Secondary Education' },
  { id: 2, value: 'post_secondary', label: 'Post-Secondary Education' },
  { id: 3, value: 'bachelors', label: 'Bachelor\'s Degree' },
  { id: 4, value: 'masters', label: 'Master\'s Degree' },
  { id: 5, value: 'doctorate', label: 'Doctorate' }
];
export const dbDegreeOptions = [
  { id: 1, value: 'MA', label: 'Master of Arts (MA)' },
  { id: 2, value: 'MS', label: 'Master of Science (MS)' },
  { id: 3, value: 'MBA', label: 'Master of Business Administration (MBA)' },
  { id: 4, value: 'PhD', label: 'Doctor of Philosophy (PhD)' },
  { id: 5, value: 'MD', label: 'Medical Doctor (MD)' },
  { id: 6, value: 'JD', label: 'Juris Doctor (JD)' }
];
export const majorOptions = [
  // Agriculture & Natural Resources
  { id: 1, value: "general_agriculture", label: "General Agriculture" },
  { id: 2, value: "agriculture_production", label: "Agriculture Production and Management" },
  { id: 3, value: "agricultural_economics", label: "Agricultural Economics" },
  { id: 4, value: "animal_sciences", label: "Animal Sciences" },
  { id: 5, value: "food_science", label: "Food Science" },
  { id: 6, value: "plant_science", label: "Plant Science and Agronomy" },
  { id: 7, value: "soil_science", label: "Soil Science" },
  { id: 8, value: "misc_agriculture", label: "Miscellaneous Agriculture" },
  { id: 9, value: "forestry", label: "Forestry" },
  { id: 10, value: "natural_resources", label: "Natural Resources Management" },
  
  // Arts
  { id: 11, value: "fine_arts", label: "Fine Arts" },
  { id: 12, value: "drama_theater", label: "Drama and Theater Arts" },
  { id: 13, value: "music", label: "Music" },
  { id: 14, value: "visual_performing_arts", label: "Visual and Performing Arts" },
  { id: 15, value: "commercial_art", label: "Commercial Art and Graphic Design" },
  { id: 16, value: "film_video_photo", label: "Film Video and Photographic Arts" },
  { id: 17, value: "studio_arts", label: "Studio Arts" },
  { id: 18, value: "misc_fine_arts", label: "Miscellaneous Fine Arts" },
  
  // Biology & Life Science
  { id: 19, value: "environmental_science", label: "Environmental Science" },
  { id: 20, value: "biology", label: "Biology" },
  { id: 21, value: "biochemical_sciences", label: "Biochemical Sciences" },
  { id: 22, value: "botany", label: "Botany" },
  { id: 23, value: "molecular_biology", label: "Molecular Biology" },
  { id: 24, value: "ecology", label: "Ecology" },
  { id: 25, value: "genetics", label: "Genetics" },
  { id: 26, value: "microbiology", label: "Microbiology" },
  { id: 27, value: "pharmacology", label: "Pharmacology" },
  { id: 28, value: "physiology", label: "Physiology" },
  { id: 29, value: "zoology", label: "Zoology" },
  { id: 30, value: "neuroscience", label: "Neuroscience" },
  { id: 31, value: "misc_biology", label: "Miscellaneous Biology" },
  { id: 32, value: "cognitive_science", label: "Cognitive Science and Biopsychology" },
  
  // Business
  { id: 33, value: "general_business", label: "General Business" },
  { id: 34, value: "accounting", label: "Accounting" },
  { id: 35, value: "actuarial_science", label: "Actuarial Science" },
  { id: 36, value: "business_management", label: "Business Management and Administration" },
  { id: 37, value: "operations_logistics", label: "Operations Logistics and E-Commerce" },
  { id: 38, value: "business_economics", label: "Business Economics" },
  { id: 39, value: "marketing_research", label: "Marketing and Marketing Research" },
  { id: 40, value: "finance", label: "Finance" },
  { id: 41, value: "human_resources", label: "Human Resources and Personnel Management" },
  { id: 42, value: "international_business", label: "International Business" },
  { id: 43, value: "hospitality_management", label: "Hospitality Management" },
  { id: 44, value: "management_info_systems", label: "Management Information Systems and Statistics" },
  { id: 45, value: "misc_business", label: "Miscellaneous Business & Medical Administration" },
  
  // Communications & Journalism
  { id: 46, value: "communications", label: "Communications" },
  { id: 47, value: "journalism", label: "Journalism" },
  { id: 48, value: "mass_media", label: "Mass Media" },
  { id: 49, value: "advertising_pr", label: "Advertising and Public Relations" },
  
  // Computers & Mathematics
  { id: 50, value: "communication_tech", label: "Communication Technologies" },
  { id: 51, value: "computer_info_systems", label: "Computer and Information Systems" },
  { id: 52, value: "computer_programming", label: "Computer Programming and Data Processing" },
  { id: 53, value: "computer_science", label: "Computer Science" },
  { id: 54, value: "information_sciences", label: "Information Sciences" },
  { id: 55, value: "computer_admin", label: "Computer Administration Management and Security" },
  { id: 56, value: "computer_networking", label: "Computer Networking and Telecommunications" },
  { id: 57, value: "mathematics", label: "Mathematics" },
  { id: 58, value: "applied_mathematics", label: "Applied Mathematics" },
  { id: 59, value: "statistics_decision", label: "Statistics and Decision Science" },
  { id: 60, value: "mathematics_cs", label: "Mathematics and Computer Science" },
  
  // Education
  { id: 61, value: "general_education", label: "General Education" },
  { id: 62, value: "educational_admin", label: "Educational Administration and Supervision" },
  { id: 63, value: "school_counseling", label: "School Student Counseling" },
  { id: 64, value: "elementary_education", label: "Elementary Education" },
  { id: 65, value: "mathematics_teacher", label: "Mathematics Teacher Education" },
  { id: 66, value: "physical_health_education", label: "Physical and Health Education Teaching" },
  { id: 67, value: "early_childhood_education", label: "Early Childhood Education" },
  { id: 68, value: "science_teacher", label: "Science and Computer Teacher Education" },
  { id: 69, value: "secondary_education", label: "Secondary Teacher Education" },
  { id: 70, value: "special_needs", label: "Special Needs Education" },
  { id: 71, value: "social_science_education", label: "Social Science or History Teacher Education" },
  { id: 72, value: "teacher_education", label: "Teacher Education: Multiple Levels" },
  { id: 73, value: "language_drama_education", label: "Language and Drama Education" },
  { id: 74, value: "art_music_education", label: "Art and Music Education" },
  { id: 75, value: "misc_education", label: "Miscellaneous Education" },
  { id: 76, value: "library_science", label: "Library Science" },
  
  // Engineering
  { id: 77, value: "architecture", label: "Architecture" },
  { id: 78, value: "general_engineering", label: "General Engineering" },
  { id: 79, value: "aerospace", label: "Aerospace Engineering" },
  { id: 80, value: "biological_engineering", label: "Biological Engineering" },
  { id: 81, value: "architectural_engineering", label: "Architectural Engineering" },
  { id: 82, value: "biomedical", label: "Biomedical Engineering" },
  { id: 83, value: "chemical", label: "Chemical Engineering" },
  { id: 84, value: "civil", label: "Civil Engineering" },
  { id: 85, value: "computer_engineering", label: "Computer Engineering" },
  { id: 86, value: "electrical", label: "Electrical Engineering" },
  { id: 87, value: "engineering_mechanics", label: "Engineering Mechanics Physics and Science" },
  { id: 88, value: "environmental_engineering", label: "Environmental Engineering" },
  { id: 89, value: "geological_engineering", label: "Geological and Geophysical Engineering" },
  { id: 90, value: "industrial_engineering", label: "Industrial and Manufacturing Engineering" },
  { id: 91, value: "materials_engineering", label: "Materials Engineering and Materials Science" },
  { id: 92, value: "mechanical", label: "Mechanical Engineering" },
  { id: 93, value: "metallurgical", label: "Metallurgical Engineering" },
  { id: 94, value: "mining_engineering", label: "Mining and Mineral Engineering" },
  { id: 95, value: "naval_engineering", label: "Naval Architecture and Marine Engineering" },
  { id: 96, value: "nuclear_engineering", label: "Nuclear Engineering" },
  { id: 97, value: "petroleum_engineering", label: "Petroleum Engineering" },
  { id: 98, value: "misc_engineering", label: "Miscellaneous Engineering" },
  { id: 99, value: "engineering_tech", label: "Engineering Technologies" },
  { id: 100, value: "engineering_industrial", label: "Engineering and Industrial Management" },
  { id: 101, value: "electrical_tech", label: "Electrical Engineering Technology" },
  { id: 102, value: "industrial_production", label: "Industrial Production Technologies" },
  { id: 103, value: "mechanical_tech", label: "Mechanical Engineering Related Technologies" },
  { id: 104, value: "misc_engineering_tech", label: "Miscellaneous Engineering Technologies" },
  { id: 105, value: "materials_science", label: "Materials Science" },
  
  // Health
  { id: 106, value: "nutrition_sciences", label: "Nutrition Sciences" },
  { id: 107, value: "general_medical", label: "General Medical and Health Services" },
  { id: 108, value: "communication_disorders", label: "Communication Disorders Sciences and Services" },
  { id: 109, value: "health_medical_admin", label: "Health and Medical Administrative Services" },
  { id: 110, value: "medical_assisting", label: "Medical Assisting Services" },
  { id: 111, value: "medical_tech", label: "Medical Technologies Technicians" },
  { id: 112, value: "health_preparatory", label: "Health and Medical Preparatory Programs" },
  { id: 113, value: "nursing", label: "Nursing" },
  { id: 114, value: "pharmacy", label: "Pharmacy Pharmaceutical Sciences and Administration" },
  { id: 115, value: "treatment_therapy", label: "Treatment Therapy Professions" },
  { id: 116, value: "community_health", label: "Community and Public Health" },
  { id: 117, value: "misc_health_medical", label: "Miscellaneous Health Medical Professions" },
  
  // Humanities & Liberal Arts
  { id: 118, value: "area_ethnic_studies", label: "Area Ethnic and Civilization Studies" },
  { id: 119, value: "linguistics", label: "Linguistics and Comparative Language and Literature" },
  { id: 120, value: "foreign_language", label: "French German Latin and Other Common Foreign Language Studies" },
  { id: 121, value: "other_foreign_language", label: "Other Foreign Languages" },
  { id: 122, value: "english", label: "English Language and Literature" },
  { id: 123, value: "composition_rhetoric", label: "Composition and Rhetoric" },
  { id: 124, value: "liberal_arts", label: "Liberal Arts" },
  { id: 125, value: "humanities", label: "Humanities" },
  { id: 126, value: "intercultural_studies", label: "Intercultural and International Studies" },
  { id: 127, value: "philosophy_religious", label: "Philosophy and Religious Studies" },
  { id: 128, value: "theology", label: "Theology and Religious Vocations" },
  { id: 129, value: "anthropology_archeology", label: "Anthropology and Archeology" },
  { id: 130, value: "art_history", label: "Art History and Criticism" },
  { id: 131, value: "history", label: "History" },
  { id: 132, value: "us_history", label: "United States History" },
  
  // Industrial Arts & Consumer Services
  { id: 133, value: "cosmetology", label: "Cosmetology Services and Culinary Arts" },
  { id: 134, value: "family_consumer_science", label: "Family and Consumer Sciences" },
  { id: 135, value: "military_tech", label: "Military Technologies" },
  { id: 136, value: "physical_fitness", label: "Physical Fitness Parks Recreation and Leisure" },
  { id: 137, value: "construction_services", label: "Construction Services" },
  { id: 138, value: "precision_production", label: "Electrical, Mechanical, and Precision Technologies and Production" },
  { id: 139, value: "transportation", label: "Transportation Sciences and Technologies" },
  
  // Law & Public Policy
  { id: 140, value: "court_reporting", label: "Court Reporting" },
  { id: 141, value: "pre_law", label: "Pre-Law and Legal Studies" },
  { id: 142, value: "criminal_justice", label: "Criminal Justice and Fire Protection" },
  { id: 143, value: "public_admin", label: "Public Administration" },
  { id: 144, value: "public_policy", label: "Public Policy" },
  
  // Physical Sciences
  { id: 145, value: "physical_sciences", label: "Physical Sciences" },
  { id: 146, value: "astronomy", label: "Astronomy and Astrophysics" },
  { id: 147, value: "atmospheric_sciences", label: "Atmospheric Sciences and Meteorology" },
  { id: 148, value: "chemistry", label: "Chemistry" },
  { id: 149, value: "geology", label: "Geology and Earth Science" },
  { id: 150, value: "geosciences", label: "Geosciences" },
  { id: 151, value: "oceanography", label: "Oceanography" },
  { id: 152, value: "physics", label: "Physics" },
  { id: 153, value: "multidisciplinary_science", label: "Multi-Disciplinary or General Science" },
  { id: 154, value: "nuclear_tech", label: "Nuclear, Industrial Radiology, and Biological Technologies" },
  
  // Psychology & Social Work
  { id: 155, value: "psychology", label: "Psychology" },
  { id: 156, value: "educational_psychology", label: "Educational Psychology" },
  { id: 157, value: "clinical_psychology", label: "Clinical Psychology" },
  { id: 158, value: "counseling_psychology", label: "Counseling Psychology" },
  { id: 159, value: "industrial_psychology", label: "Industrial and Organizational Psychology" },
  { id: 160, value: "social_psychology", label: "Social Psychology" },
  { id: 161, value: "misc_psychology", label: "Miscellaneous Psychology" },
  { id: 162, value: "human_services", label: "Human Services and Community Organization" },
  { id: 163, value: "social_work", label: "Social Work" },
  
  // Social Science
  { id: 164, value: "interdisciplinary_social_sciences", label: "Interdisciplinary Social Sciences" },
  { id: 165, value: "general_social_sciences", label: "General Social Sciences" },
  { id: 166, value: "economics", label: "Economics" },
  { id: 167, value: "criminology", label: "Criminology" },
  { id: 168, value: "geography", label: "Geography" },
  { id: 169, value: "international_relations", label: "International Relations" },
  { id: 170, value: "political_science", label: "Political Science and Government" },
  { id: 171, value: "sociology", label: "Sociology" },
  { id: 172, value: "misc_social_sciences", label: "Miscellaneous Social Sciences" }
];

export const countryOptions = countryList().getData();