import { useEffect } from 'react';
import { Button } from "@/app/components/ui";

export default function TermsOfService() {
  // Set the document title when component mounts
  useEffect(() => {
    document.title = "Terms of Service - GradAid";
    
    // Optional: restore the previous title when component unmounts
    return () => {
      document.title = "GradAid";
    };
  }, []);
  
  const handleGoBack = () => {
    window.history.back();
  };
  
  return (
    <div className="container mx-auto py-8 px-4 max-w-4xl">
      <div className="prose prose-lg max-w-none">
        <h1 className="text-3xl font-bold mb-6">Terms of Service</h1>
        
        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">1. Introduction</h2>
          <p>Welcome to GradAid. By accessing or using our service, you agree to be bound by these Terms of Service.</p>
        </section>
        
        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">2. Definitions</h2>
          <p>"Service" refers to the GradAid application.</p>
          <p>"Users" refers to individuals who access or use the Service.</p>
        </section>
        
        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">3. Use of Service</h2>
          <p>You agree to use the Service only for lawful purposes and in accordance with these Terms.</p>
          <p>You agree not to use the Service in any way that could damage or impair the Service or interfere with any other party's use of the Service.</p>
        </section>
        
        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">5. Privacy</h2>
          <p>Your use of the Service is also governed by our Privacy Policy.</p>
        </section>
        
        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">6. Changes to Terms</h2>
          <p>We reserve the right to modify these Terms at any time. We will provide notice of significant changes.</p>
        </section>
        
        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">7. Disclaimer</h2>
          <p className="italic">Please note that these Terms of Service were generated by artificial intelligence and may not address all legal requirements or considerations. This document should not be considered as formal legal advice and should be reviewed by qualified legal professionals before implementation or reliance.</p>
          <p className="font-semibold mt-2">For questions or concerns about these Terms, please contact our legal department for a properly vetted document.</p>
        </section>

        <div className="mb-8 text-center">
          <img 
            src="https://cdn.7tv.app/emote/01F6N373G0000F76KNAAV177D4/4x.avif" 
            alt="Terms of Service Icon" 
            className="mx-auto mb-4"
          />
        </div>

        <div className="flex justify-center mt-8">
          <Button
            variant="outline"
            onClick={handleGoBack}
            className="px-6"
          >
            Go Back
          </Button>
        </div>
      </div>
    </div>
  );
}