import { Button } from "@/components/ui";

export default function PrivacyPolicy() {
    const handleGoBack = () => {
        window.history.back();
    };

    return (
        <div className="container max-w-3xl py-16 mx-auto">
            <h1 className="text-4xl font-bold mb-6">
                Privacy Policy
            </h1>

            <div className="mb-8">
                <p className="text-sm text-muted-foreground italic text-left">
                    <em>Disclaimer: This privacy policy was generated by AI and should be reviewed by a legal professional before use.</em>
                </p>
            </div>

            <h2 className="text-2xl font-semibold mt-8 mb-4">
                1. Introduction
            </h2>
            <p className="mb-4 text-left">
                Welcome to GradAid. We respect your privacy and are committed to protecting your personal data. This privacy policy will inform you about how we look after your personal data when you visit our website and tell you about your privacy rights and how the law protects you.
            </p>

            <h2 className="text-2xl font-semibold mt-8 mb-4">
                2. Data We Collect
            </h2>
            <p className="mb-4 text-left">
                We may collect, use, store and transfer different kinds of personal data about you which we have grouped together as follows:
            </p>
            <ul className="list-disc pl-6 mb-6 space-y-1">
                <li className="text-left">Identity Data includes first name, last name, username or similar identifier.</li>
                <li className="text-left">Contact Data includes email address and telephone numbers.</li>
                <li className="text-left">Technical Data includes internet protocol (IP) address, browser type and version, time zone setting and location, browser plug-in types and versions, operating system and platform, and other technology on the devices you use to access this website.</li>
                <li className="text-left">Usage Data includes information about how you use our website and services.</li>
            </ul>

            <h2 className="text-2xl font-semibold mt-8 mb-4">
                3. How We Use Your Data
            </h2>
            <p className="mb-4 text-left">
                We will only use your personal data when the law allows us to. Most commonly, we will use your personal data in the following circumstances:
            </p>
            <ul className="list-disc pl-6 mb-6 space-y-1">
                <li className="text-left">To provide and maintain our service.</li>
                <li className="text-left">To notify you about changes to our service.</li>
                <li className="text-left">To allow you to participate in interactive features of our service when you choose to do so.</li>
                <li className="text-left">To provide customer support.</li>
                <li className="text-left">To gather analysis or valuable information so that we can improve our service.</li>
                <li className="text-left">To monitor the usage of our service.</li>
                <li className="text-left">To detect, prevent and address technical issues.</li>
            </ul>

            <h2 className="text-2xl font-semibold mt-8 mb-4">
                4. Data Security
            </h2>
            <p className="mb-4 text-left">
                We have put in place appropriate security measures to prevent your personal data from being accidentally lost, used or accessed in an unauthorized way, altered or disclosed. In addition, we limit access to your personal data to those employees, agents, contractors and other third parties who have a business need to know.
            </p>

            <h2 className="text-2xl font-semibold mt-8 mb-4">
                5. Data Retention
            </h2>
            <p className="mb-4 text-left">
                We will only retain your personal data for as long as reasonably necessary to fulfill the purposes we collected it for, including for the purposes of satisfying any legal, regulatory, tax, accounting or reporting requirements.
            </p>

            <h2 className="text-2xl font-semibold mt-8 mb-4">
                6. Your Legal Rights
            </h2>
            <p className="mb-4 text-left">
                Under certain circumstances, you have rights under data protection laws in relation to your personal data, including the right to:
            </p>
            <ul className="list-disc pl-6 mb-6 space-y-1">
                <li className="text-left">Request access to your personal data.</li>
                <li className="text-left">Request correction of your personal data.</li>
                <li className="text-left">Request erasure of your personal data.</li>
                <li className="text-left">Object to processing of your personal data.</li>
                <li className="text-left">Request restriction of processing your personal data.</li>
                <li className="text-left">Request transfer of your personal data.</li>
                <li className="text-left">Right to withdraw consent.</li>
            </ul>

            <h2 className="text-2xl font-semibold mt-8 mb-4">
                7. Changes to This Privacy Policy
            </h2>
            <p className="mb-4 text-left">
                We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page and updating the "Last Updated" date.
            </p>

            <h2 className="text-2xl font-semibold mt-8 mb-4">
                8. Contact Us
            </h2>
            <p className="mb-4 text-left">
                If you have any questions about this Privacy Policy, do something else with your life:
            </p>
            <div className="mb-8 text-center">
                <img
                    src="https://cdn.7tv.app/emote/01F9Q9PA100009VDTF4G64R32V/4x.avif"
                    alt="Terms of Service Icon"
                    className="mx-auto mb-4"
                />
            </div>
            <div className="flex justify-center mt-8">
                <Button
                    variant="outline"
                    onClick={handleGoBack}
                    className="px-6"
                >
                    Go Back
                </Button>
            </div>
        </div>
    );
}